## Partie 1
Implémenter la méthode des treillis pour le calcul des prix d’options (pour les différents types d’options). 
On testera la méthode sur différentes instances en faisant varier les paramètres (N : le nombre de périodes, r : taux de crédit, d et u). 
On essayera de considérer aussi des instances assez larges. 

In [3]:
import matplotlib.pyplot as plt
import numpy as np

In [4]:
def assetTreeValue(n, S, u, d):  
    asset = np.zeros((n+1,n+1))
    asset[0,0] = S
    for i in range(1,n+1):
        asset[i,0] = asset[i-1,0]*u
        for j in range(1,i+1):
            asset[i,j] = asset[i-1,j-1]*d
    return asset    

In [5]:
def calculationOptionPrice(n, assetValue, K, r, u, d, PutCall, optiontype):
    value = np.zeros((n+1,n+1))
    proba = (1+r-d)/(u-d)
    print('Probabilité Risque-neutre : ',proba)
    
    for j in range(n+1):
        if PutCall=="C": # Call
            payoff = max(0, (assetValue[n,j]-K))
            value[n,j] = payoff
        elif PutCall=="P": #Put
            print(j)
            payoff = max(0, (K-assetValue[n,j]))
            value[n,j] = payoff
    
    if optiontype == "USA":
         for i in range(n-1,-1,-1):
            for j in range(i+1):
                if PutCall=="P":
                    value[i,j] = max(0, K-assetValue[i,j], (1/1+r)*(proba*value[i+1,j]+(1-proba)*value[i+1,j+1]))
                elif PutCall=="C":
                    value[i,j] = max(0, assetValue[i,j]-K, (1/1+r)*(proba*value[i+1,j]+(1-proba)*value[i+1,j+1]))
    
    if optiontype == "EUR":
         for i in range(n-1,-1,-1):
            for j in range(i+1):
                value[i,j] = (1/1+r)*(proba*value[i+1,j]+(1-proba)*value[i+1,j+1])
                    
    return value

In [6]:
# test de visualisation
def drawAssetTree(n, asset):
    positionX = np.zeros((n+1,n+1))
    positionY = np.zeros((n+1,n+1))
    positionX[0][0] = 0.10
    positionY = 0.5
    
    plt.xlim(0,1) 
    plt.figtext(0.10,0.5,asset[0,0])
    
    for i in range(0,n+1):
        for j in range(i):
            plt.figtext(i-0.4,i+0.2,asset[i,j])
            plt.annotate('',xy=(i-0.4,i+0.2), xytext=(0.10,0.5), arrowprops=dict(facecolor='g',shrink=0.01))

    plt.axis('off')
    plt.show()

In [7]:
# test de visualisation
def drawTree(n, asset):
    plt.xlim(0,1) 
    plt.figtext(0.10,0.5,asset[0,0])
    
    plt.figtext(0.6,0.5+0.20,asset[1,0])
    plt.figtext(0.6,0.5-0.20,asset[1,1])
    
    plt.annotate('',xy=(0.6,0.5+0.25), xytext=(0.1,0.5), arrowprops=dict(facecolor='g',shrink=0.01))
    plt.annotate('',xy=(0.6,0.5-0.25), xytext=(0.1,0.5), arrowprops=dict(facecolor='g',shrink=0.01))
    
    plt.figtext(0.9,0.5+0.35,asset[2,0])
    plt.figtext(0.9,0.5,asset[2,1])
    plt.figtext(0.9,0.5-0.35,asset[2,2])
    
    plt.annotate('',xy=(0.9,0.5+0.40), xytext=(0.7,0.5+0.25), arrowprops=dict(facecolor='g',shrink=0.01))
    plt.annotate('',xy=(0.9,0.5), xytext=(0.7,0.5+0.25), arrowprops=dict(facecolor='g',shrink=0.01))
    
    plt.annotate('',xy=(0.9,0.5), xytext=(0.7,0.5-0.25), arrowprops=dict(facecolor='g',shrink=0.01))
    plt.annotate('',xy=(0.9,0.5-0.4), xytext=(0.7,0.5-0.25), arrowprops=dict(facecolor='g',shrink=0.01))
    
    plt.axis('off')
    plt.show()

In [8]:
asset = assetTreeValue(2, 100, 1.1, 0.9)
print(asset)
print(' ')
#drawTree(2, asset)
optionvalue = calculationOptionPrice(2, asset, 91, 0.05, 1.1, 0.9, "C", "EUR")

print(' ')
print(optionvalue[0][0])
#drawTree(2, optionvalue)

[[100.   0.   0.]
 [110.  90.   0.]
 [121.  99.  81.]]
 
Probabilité Risque-neutre :  0.7499999999999999
 
21.91218750000002


## Partie 2
Ecrire le modèle qui permet de minimiser la CVaR pour une probabilité donnée  (On donne le modèle général avec un nombre d’actifs n, un nombre de scénarios S, un vecteur rendement  et un rendement minimum R. 

<img src="pics\Partie 2.png" width="480" />

In [68]:
from scipy.optimize import minimize

In [69]:
# X[0] Gamma, X[1...N] Actifs risqués 
def func_minimise_ES(X):
    sum = 0
    loose_function = 0
    for i in range(S):
        for j in range (1, X.size):
            loose_function = loose_function + max(((b[j]-Y[i])*X[j]-X[0]),0)
    return X[0] + (1/(1-alpha)*S)*loose_function

In [70]:
# S fois cette contrainte
def constraint1(X,s):
    sum = 0
    for j in range (1,X.size):
        sum = sum + (b[j]-Y[s])*X[j]
        
    return max((sum-X[0]),0) - (sum-X[0])

In [71]:
# S fois cette contrainte
def constraint2(X,s):
    sum = 0
    for j in range (1,X.size):
        sum = sum + (b[j]-Y[s])*X[j]
    
    return max((sum-X[0]),0)-0

In [72]:
def constraint3(X):
    sum = 1
    for i in range(1,X.size):
        sum = sum - X[i]
    
    return sum

In [73]:
def minimise_ES_constraint4(X):
    sum = 0
    for i in range(1,X.size):
        sum += X[i]*E[i]
        
    return sum - R

#### Fonctions pour la compréhension logique : 

In [74]:
def rendement(X):
    sum = 0
    for i in range(1,X.size):
        sum += X[i]*E[i]
        
    return sum

In [75]:
def loose_function(X):
    loose_function = 0
    for i in range(S):
        for j in range (1, X.size):
            loose_function = loose_function + max(((b[j]-Y[i])*X[j]-X[0]),0)
    return loose_function

#### Générateur de scénarios :

In [111]:
import random as rd

In [134]:
def generateY(S):
    Y = []
    for i in range(S):
        Y.append(rd.normalvariate(0,3)/100) 
    return Y
S= 5
print(generateY(5))

[0.013340067448309834, 0.03961175772606749, 0.005421825504439209, -0.01909694681256942, 0.02186318628332078]


### Exécution

#### General Informations : 

In [141]:
alpha = 0.99 # Probabilité
R = 0.10 # Rentabilité

#### Assets Informations :

In [142]:
Nb_Assets = 5

X = np.array([1, 0.20, 0.20, 0.20, 0.20, 0.20]) # Réparitition des actifs,  Attention : X[0] == gamma
b = np.array([0, 10, 10, 10, 10, 10]) # Prix des obligations, b[0]=0 pour la fonction objective
E = np.array([0, 0.1073, 0.00415, 0.0627, 0.1045, 0,1235]) # Espérence de rendement des actifs

print('X : ', X)
print('b : ', b)
print('E : ', E)

X :  [1.  0.2 0.2 0.2 0.2 0.2]
b :  [ 0 10 10 10 10 10]
E :  [0.000e+00 1.073e-01 4.150e-03 6.270e-02 1.045e-01 0.000e+00 1.235e+03]


#### Scénarios Informations :

In [143]:
S = 5 # Nombre de scénarios
Y = np.array(generateY(5)) # vecteur de probabilités
print('Y : ', Y)

Y :  [ 0.01320443  0.02392726 -0.03667267 -0.05152686 -0.02561872]


#### Lancement :

In [144]:
print('Function initale (CVaR): ', func_minimise_ES(X))
print('Function de perte initial : ', loose_function(X))
print('Gamma initial : ', X[0])
print('1 - Répartition initiale : ', constraint3(X))
print('Rendement initial : ', rendement(X))
print('Rendement initial - Rendement espéré : ', minimise_ES_constraint4(X), '\n')



# constraints
Const1 = [] # S*contrainte 
Const2 = [] # S*contrainte
for i in range(S):
    Const1.append({'type':'ineq','args' : (i,) , 'fun': constraint1})
    Const2.append({'type':'ineq','args' : (i,)  , 'fun': constraint2}) 

ineq_cons = []
ineq_cons = (Const1 + Const2 + [{'type':'eq','fun': constraint3}, {'type':'ineq','fun': minimise_ES_constraint4}])


# bonds 
bond = (0, 1.0)
ineq_bond = ((None, None),)
for i in range(Nb_Assets):
    ineq_bond = ineq_bond + (bond,) # x1 >= 0, x2 >= 0, ...


sol = minimize(func_minimise_ES,
               x0=X, 
               method='SLSQP',  # Il faut trouver la bonne méthode
               bounds=ineq_bond, 
               options={'disp': True},
               constraints=ineq_cons)
print(sol, '\n')
Res = sol.x

print('Function finale (CVaR) : ', func_minimise_ES(Res))
print('Function de perte finale : ', loose_function(Res))
print('Gamma final : ', Res[0])
print('1 - Répartition obtenue : ', constraint3(Res))
print('Rendement final : ', rendement(Res))
print('Rendement final - Rendement espéré :  ', minimise_ES_constraint4(Res))


Function initale (CVaR):  12539.34328250352
Function de perte initial :  25.076686565007062
Gamma initial :  1.0
1 - Répartition initiale :  5.551115123125783e-17
Rendement initial :  0.05573000000000001
Rendement initial - Rendement espéré :  -0.04427 

Optimization terminated successfully    (Exit mode 0)
            Current function value: 4.339420816829722
            Iterations: 48
            Function evaluations: 504
            Gradient evaluations: 48
     fun: 4.339420816829722
     jac: array([1., 0., 0., 0., 0., 0.])
 message: 'Optimization terminated successfully'
    nfev: 504
     nit: 48
    njev: 48
  status: 0
 success: True
       x: array([4.33942082e+00, 4.31717555e-01, 1.55232513e-15, 1.36568617e-01,
       4.31713828e-01, 1.39374169e-15]) 

Function finale (CVaR) :  4.339420816829722
Function de perte finale :  0
Gamma final :  4.339420816829722
1 - Répartition obtenue :  -3.292407558569983e-14
Rendement final :  0.10000024096997762
Rendement final - Rendement es

## Partie 3 (à revoir)

Considérons le modèle de Markowitz maximisant le rendement du portefeuille et assurant une CVaR  ne dépassant pas un certain seuil.  
Ecrire le modèle correspondant et le résoudre pour certaines données aléatoires. 

<img src="pics\Partie 3.png" width="494" />

In [357]:
from scipy.optimize import linprog

In [347]:
# Définition des nouvelles varibales 

J = np.array([0, 0.50, 0.25, 0.25]) # Ensemble d'indices sur les différentes valeurs disponibles
U = np.array([0, 1, 3, 4 ]) # Risque maximal toléré pour une valeur Alpha j

In [348]:
# X[0] Gamma, X[1...N] Actifs risqués 
def func_maximise_yield(X):
    rendement = 0
    for i in range(1,X.size):
        rendement += X[i]*E[i]
    return rendement

In [349]:
# S fois cette contrainte
def maximise_yield_constraint1(X,alpha_j):
    sum = 0
    for i in range(S):
        loose_function = 0
        for j in range (1, X.size):
            loose_function = loose_function + max(((b[j]-Y[i])*X[j]-X[0]),0)
            
    return U[alpha_j] - (X[0] + (1/(1-alpha)*S)*loose_function) 

In [358]:
# constraints
ineq_cons = ([{'type':'ineq','fun': lambda i : maximise_yield_constraint1(X,i)} for i in range(J.size)] +
            [{'type':'ineq','fun': lambda i : constraint2(X,i)} for i in range(S)] +
            [{'type':'ineq','fun': lambda i : constraint1(X,i)} for i in range(S)] + 
             [{'type':'eq','fun': constraint3}])

# bonds 
bond = (0, 1.0)
ineq_bond = [(None,None)] + [(0,1.0) for i in range(X.size-1)] # x1 >= 0, x2 >= 0, ...


In [451]:
for i in range(5):
    def Constraint_i():
        return i 
    
print(Constraint_i())

4
